# Generated by Django 3.0.7 on 2020-07-26 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200726_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(choices=[(1, 'Seller'), (2, 'Buyer')], default=1),
        ),
    ]
