# Generated by Django 3.0.7 on 2020-07-01 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_percentage',
            field=models.IntegerField(blank=True, help_text='Enter the number for discount percentage like 45', null=True),
        ),
    ]
