# Generated by Django 3.0.7 on 2020-07-01 11:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200701_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount_percentage',
            field=models.IntegerField(blank=True, help_text='Enter the number for discount percentage like 45', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
