# Generated by Django 3.0.7 on 2020-07-01 17:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20200701_1105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.AddField(
            model_name='product',
            name='long_description',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='Long Description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='Short Description'),
            preserve_default=False,
        ),
    ]
